channels:
  - conda-forge
  - defaults
dependencies:
  - prospect==0.1.0
  - python=3.8.6
  - geopandas=0.8.2
  - descartes=1.1.0
  - jupyter=1.0.0
  - jupyterlab=3.0.5
  - matplotlib=3.3.3
  - seaborn=0.11.1
  - numpy=1.19.5
  - pandas=1.2.1
  - scipy=1.6.0
  - tqdm=4.56.0
